/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalHierarchies } from "./ApprovalHierarchies";
import { ApprovalHierarchiesCountArgs } from "./ApprovalHierarchiesCountArgs";
import { ApprovalHierarchiesFindManyArgs } from "./ApprovalHierarchiesFindManyArgs";
import { ApprovalHierarchiesFindUniqueArgs } from "./ApprovalHierarchiesFindUniqueArgs";
import { DeleteApprovalHierarchiesArgs } from "./DeleteApprovalHierarchiesArgs";
import { ApprovalHierarchiesService } from "../approvalHierarchies.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApprovalHierarchies)
export class ApprovalHierarchiesResolverBase {
  constructor(
    protected readonly service: ApprovalHierarchiesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "read",
    possession: "any",
  })
  async _approvalHierarchiesItemsMeta(
    @graphql.Args() args: ApprovalHierarchiesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApprovalHierarchies])
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "read",
    possession: "any",
  })
  async approvalHierarchiesItems(
    @graphql.Args() args: ApprovalHierarchiesFindManyArgs
  ): Promise<ApprovalHierarchies[]> {
    return this.service.approvalHierarchiesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApprovalHierarchies, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "read",
    possession: "own",
  })
  async approvalHierarchies(
    @graphql.Args() args: ApprovalHierarchiesFindUniqueArgs
  ): Promise<ApprovalHierarchies | null> {
    const result = await this.service.approvalHierarchies(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ApprovalHierarchies)
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "delete",
    possession: "any",
  })
  async deleteApprovalHierarchies(
    @graphql.Args() args: DeleteApprovalHierarchiesArgs
  ): Promise<ApprovalHierarchies | null> {
    try {
      return await this.service.deleteApprovalHierarchies(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
