/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ApprovalHierarchiesService } from "../approvalHierarchies.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalHierarchiesCreateInput } from "./ApprovalHierarchiesCreateInput";
import { ApprovalHierarchies } from "./ApprovalHierarchies";
import { ApprovalHierarchiesFindManyArgs } from "./ApprovalHierarchiesFindManyArgs";
import { ApprovalHierarchiesWhereUniqueInput } from "./ApprovalHierarchiesWhereUniqueInput";
import { ApprovalHierarchiesUpdateInput } from "./ApprovalHierarchiesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ApprovalHierarchiesControllerBase {
  constructor(
    protected readonly service: ApprovalHierarchiesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ApprovalHierarchies })
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createApprovalHierarchies(
    @common.Body() data: ApprovalHierarchiesCreateInput
  ): Promise<ApprovalHierarchies> {
    return await this.service.createApprovalHierarchies({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ApprovalHierarchies] })
  @ApiNestedQuery(ApprovalHierarchiesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async approvalHierarchiesItems(
    @common.Req() request: Request
  ): Promise<ApprovalHierarchies[]> {
    const args = plainToClass(ApprovalHierarchiesFindManyArgs, request.query);
    return this.service.approvalHierarchiesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ApprovalHierarchies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async approvalHierarchies(
    @common.Param() params: ApprovalHierarchiesWhereUniqueInput
  ): Promise<ApprovalHierarchies | null> {
    const result = await this.service.approvalHierarchies({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ApprovalHierarchies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateApprovalHierarchies(
    @common.Param() params: ApprovalHierarchiesWhereUniqueInput,
    @common.Body() data: ApprovalHierarchiesUpdateInput
  ): Promise<ApprovalHierarchies | null> {
    try {
      return await this.service.updateApprovalHierarchies({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ApprovalHierarchies })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ApprovalHierarchies",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteApprovalHierarchies(
    @common.Param() params: ApprovalHierarchiesWhereUniqueInput
  ): Promise<ApprovalHierarchies | null> {
    try {
      return await this.service.deleteApprovalHierarchies({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
