/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseCategories } from "./ExpenseCategories";
import { ExpenseCategoriesCountArgs } from "./ExpenseCategoriesCountArgs";
import { ExpenseCategoriesFindManyArgs } from "./ExpenseCategoriesFindManyArgs";
import { ExpenseCategoriesFindUniqueArgs } from "./ExpenseCategoriesFindUniqueArgs";
import { DeleteExpenseCategoriesArgs } from "./DeleteExpenseCategoriesArgs";
import { ExpenseCategoriesService } from "../expenseCategories.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExpenseCategories)
export class ExpenseCategoriesResolverBase {
  constructor(
    protected readonly service: ExpenseCategoriesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExpenseCategories",
    action: "read",
    possession: "any",
  })
  async _expenseCategoriesItemsMeta(
    @graphql.Args() args: ExpenseCategoriesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExpenseCategories])
  @nestAccessControl.UseRoles({
    resource: "ExpenseCategories",
    action: "read",
    possession: "any",
  })
  async expenseCategoriesItems(
    @graphql.Args() args: ExpenseCategoriesFindManyArgs
  ): Promise<ExpenseCategories[]> {
    return this.service.expenseCategoriesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExpenseCategories, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExpenseCategories",
    action: "read",
    possession: "own",
  })
  async expenseCategories(
    @graphql.Args() args: ExpenseCategoriesFindUniqueArgs
  ): Promise<ExpenseCategories | null> {
    const result = await this.service.expenseCategories(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExpenseCategories)
  @nestAccessControl.UseRoles({
    resource: "ExpenseCategories",
    action: "delete",
    possession: "any",
  })
  async deleteExpenseCategories(
    @graphql.Args() args: DeleteExpenseCategoriesArgs
  ): Promise<ExpenseCategories | null> {
    try {
      return await this.service.deleteExpenseCategories(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
