/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TaxManagement } from "./TaxManagement";
import { TaxManagementCountArgs } from "./TaxManagementCountArgs";
import { TaxManagementFindManyArgs } from "./TaxManagementFindManyArgs";
import { TaxManagementFindUniqueArgs } from "./TaxManagementFindUniqueArgs";
import { DeleteTaxManagementArgs } from "./DeleteTaxManagementArgs";
import { TaxManagementService } from "../taxManagement.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => TaxManagement)
export class TaxManagementResolverBase {
  constructor(
    protected readonly service: TaxManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TaxManagement",
    action: "read",
    possession: "any",
  })
  async _taxManagementsMeta(
    @graphql.Args() args: TaxManagementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [TaxManagement])
  @nestAccessControl.UseRoles({
    resource: "TaxManagement",
    action: "read",
    possession: "any",
  })
  async taxManagements(
    @graphql.Args() args: TaxManagementFindManyArgs
  ): Promise<TaxManagement[]> {
    return this.service.taxManagements(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => TaxManagement, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TaxManagement",
    action: "read",
    possession: "own",
  })
  async taxManagement(
    @graphql.Args() args: TaxManagementFindUniqueArgs
  ): Promise<TaxManagement | null> {
    const result = await this.service.taxManagement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => TaxManagement)
  @nestAccessControl.UseRoles({
    resource: "TaxManagement",
    action: "delete",
    possession: "any",
  })
  async deleteTaxManagement(
    @graphql.Args() args: DeleteTaxManagementArgs
  ): Promise<TaxManagement | null> {
    try {
      return await this.service.deleteTaxManagement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
