/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StatutoryComplianceService } from "../statutoryCompliance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StatutoryComplianceCreateInput } from "./StatutoryComplianceCreateInput";
import { StatutoryCompliance } from "./StatutoryCompliance";
import { StatutoryComplianceFindManyArgs } from "./StatutoryComplianceFindManyArgs";
import { StatutoryComplianceWhereUniqueInput } from "./StatutoryComplianceWhereUniqueInput";
import { StatutoryComplianceUpdateInput } from "./StatutoryComplianceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StatutoryComplianceControllerBase {
  constructor(
    protected readonly service: StatutoryComplianceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StatutoryCompliance })
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStatutoryCompliance(
    @common.Body() data: StatutoryComplianceCreateInput
  ): Promise<StatutoryCompliance> {
    return await this.service.createStatutoryCompliance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [StatutoryCompliance] })
  @ApiNestedQuery(StatutoryComplianceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statutoryCompliances(
    @common.Req() request: Request
  ): Promise<StatutoryCompliance[]> {
    const args = plainToClass(StatutoryComplianceFindManyArgs, request.query);
    return this.service.statutoryCompliances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StatutoryCompliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async statutoryCompliance(
    @common.Param() params: StatutoryComplianceWhereUniqueInput
  ): Promise<StatutoryCompliance | null> {
    const result = await this.service.statutoryCompliance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StatutoryCompliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStatutoryCompliance(
    @common.Param() params: StatutoryComplianceWhereUniqueInput,
    @common.Body() data: StatutoryComplianceUpdateInput
  ): Promise<StatutoryCompliance | null> {
    try {
      return await this.service.updateStatutoryCompliance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StatutoryCompliance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStatutoryCompliance(
    @common.Param() params: StatutoryComplianceWhereUniqueInput
  ): Promise<StatutoryCompliance | null> {
    try {
      return await this.service.deleteStatutoryCompliance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
