/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StatutoryCompliance } from "./StatutoryCompliance";
import { StatutoryComplianceCountArgs } from "./StatutoryComplianceCountArgs";
import { StatutoryComplianceFindManyArgs } from "./StatutoryComplianceFindManyArgs";
import { StatutoryComplianceFindUniqueArgs } from "./StatutoryComplianceFindUniqueArgs";
import { DeleteStatutoryComplianceArgs } from "./DeleteStatutoryComplianceArgs";
import { StatutoryComplianceService } from "../statutoryCompliance.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => StatutoryCompliance)
export class StatutoryComplianceResolverBase {
  constructor(
    protected readonly service: StatutoryComplianceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "read",
    possession: "any",
  })
  async _statutoryCompliancesMeta(
    @graphql.Args() args: StatutoryComplianceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [StatutoryCompliance])
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "read",
    possession: "any",
  })
  async statutoryCompliances(
    @graphql.Args() args: StatutoryComplianceFindManyArgs
  ): Promise<StatutoryCompliance[]> {
    return this.service.statutoryCompliances(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => StatutoryCompliance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "read",
    possession: "own",
  })
  async statutoryCompliance(
    @graphql.Args() args: StatutoryComplianceFindUniqueArgs
  ): Promise<StatutoryCompliance | null> {
    const result = await this.service.statutoryCompliance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StatutoryCompliance)
  @nestAccessControl.UseRoles({
    resource: "StatutoryCompliance",
    action: "delete",
    possession: "any",
  })
  async deleteStatutoryCompliance(
    @graphql.Args() args: DeleteStatutoryComplianceArgs
  ): Promise<StatutoryCompliance | null> {
    try {
      return await this.service.deleteStatutoryCompliance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
