/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ExpenseRequestsService } from "../expenseRequests.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseRequestsCreateInput } from "./ExpenseRequestsCreateInput";
import { ExpenseRequests } from "./ExpenseRequests";
import { ExpenseRequestsFindManyArgs } from "./ExpenseRequestsFindManyArgs";
import { ExpenseRequestsWhereUniqueInput } from "./ExpenseRequestsWhereUniqueInput";
import { ExpenseRequestsUpdateInput } from "./ExpenseRequestsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ExpenseRequestsControllerBase {
  constructor(
    protected readonly service: ExpenseRequestsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ExpenseRequests })
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createExpenseRequests(
    @common.Body() data: ExpenseRequestsCreateInput
  ): Promise<ExpenseRequests> {
    return await this.service.createExpenseRequests({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ExpenseRequests] })
  @ApiNestedQuery(ExpenseRequestsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expenseRequestsItems(
    @common.Req() request: Request
  ): Promise<ExpenseRequests[]> {
    const args = plainToClass(ExpenseRequestsFindManyArgs, request.query);
    return this.service.expenseRequestsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ExpenseRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async expenseRequests(
    @common.Param() params: ExpenseRequestsWhereUniqueInput
  ): Promise<ExpenseRequests | null> {
    const result = await this.service.expenseRequests({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ExpenseRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateExpenseRequests(
    @common.Param() params: ExpenseRequestsWhereUniqueInput,
    @common.Body() data: ExpenseRequestsUpdateInput
  ): Promise<ExpenseRequests | null> {
    try {
      return await this.service.updateExpenseRequests({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ExpenseRequests })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteExpenseRequests(
    @common.Param() params: ExpenseRequestsWhereUniqueInput
  ): Promise<ExpenseRequests | null> {
    try {
      return await this.service.deleteExpenseRequests({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
