/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ExpenseRequests } from "./ExpenseRequests";
import { ExpenseRequestsCountArgs } from "./ExpenseRequestsCountArgs";
import { ExpenseRequestsFindManyArgs } from "./ExpenseRequestsFindManyArgs";
import { ExpenseRequestsFindUniqueArgs } from "./ExpenseRequestsFindUniqueArgs";
import { DeleteExpenseRequestsArgs } from "./DeleteExpenseRequestsArgs";
import { ExpenseRequestsService } from "../expenseRequests.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExpenseRequests)
export class ExpenseRequestsResolverBase {
  constructor(
    protected readonly service: ExpenseRequestsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "read",
    possession: "any",
  })
  async _expenseRequestsItemsMeta(
    @graphql.Args() args: ExpenseRequestsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExpenseRequests])
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "read",
    possession: "any",
  })
  async expenseRequestsItems(
    @graphql.Args() args: ExpenseRequestsFindManyArgs
  ): Promise<ExpenseRequests[]> {
    return this.service.expenseRequestsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExpenseRequests, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "read",
    possession: "own",
  })
  async expenseRequests(
    @graphql.Args() args: ExpenseRequestsFindUniqueArgs
  ): Promise<ExpenseRequests | null> {
    const result = await this.service.expenseRequests(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExpenseRequests)
  @nestAccessControl.UseRoles({
    resource: "ExpenseRequests",
    action: "delete",
    possession: "any",
  })
  async deleteExpenseRequests(
    @graphql.Args() args: DeleteExpenseRequestsArgs
  ): Promise<ExpenseRequests | null> {
    try {
      return await this.service.deleteExpenseRequests(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
