/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RazorPayXIntegrationService } from "../razorPayXIntegration.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RazorPayXIntegrationCreateInput } from "./RazorPayXIntegrationCreateInput";
import { RazorPayXIntegration } from "./RazorPayXIntegration";
import { RazorPayXIntegrationFindManyArgs } from "./RazorPayXIntegrationFindManyArgs";
import { RazorPayXIntegrationWhereUniqueInput } from "./RazorPayXIntegrationWhereUniqueInput";
import { RazorPayXIntegrationUpdateInput } from "./RazorPayXIntegrationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RazorPayXIntegrationControllerBase {
  constructor(
    protected readonly service: RazorPayXIntegrationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RazorPayXIntegration })
  @nestAccessControl.UseRoles({
    resource: "RazorPayXIntegration",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRazorPayXIntegration(
    @common.Body() data: RazorPayXIntegrationCreateInput
  ): Promise<RazorPayXIntegration> {
    return await this.service.createRazorPayXIntegration({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RazorPayXIntegration] })
  @ApiNestedQuery(RazorPayXIntegrationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RazorPayXIntegration",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async razorPayXIntegrations(
    @common.Req() request: Request
  ): Promise<RazorPayXIntegration[]> {
    const args = plainToClass(RazorPayXIntegrationFindManyArgs, request.query);
    return this.service.razorPayXIntegrations({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RazorPayXIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RazorPayXIntegration",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async razorPayXIntegration(
    @common.Param() params: RazorPayXIntegrationWhereUniqueInput
  ): Promise<RazorPayXIntegration | null> {
    const result = await this.service.razorPayXIntegration({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RazorPayXIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RazorPayXIntegration",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRazorPayXIntegration(
    @common.Param() params: RazorPayXIntegrationWhereUniqueInput,
    @common.Body() data: RazorPayXIntegrationUpdateInput
  ): Promise<RazorPayXIntegration | null> {
    try {
      return await this.service.updateRazorPayXIntegration({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RazorPayXIntegration })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RazorPayXIntegration",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRazorPayXIntegration(
    @common.Param() params: RazorPayXIntegrationWhereUniqueInput
  ): Promise<RazorPayXIntegration | null> {
    try {
      return await this.service.deleteRazorPayXIntegration({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
