/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WarrantyPeriodsService } from "../warrantyPeriods.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WarrantyPeriodsCreateInput } from "./WarrantyPeriodsCreateInput";
import { WarrantyPeriods } from "./WarrantyPeriods";
import { WarrantyPeriodsFindManyArgs } from "./WarrantyPeriodsFindManyArgs";
import { WarrantyPeriodsWhereUniqueInput } from "./WarrantyPeriodsWhereUniqueInput";
import { WarrantyPeriodsUpdateInput } from "./WarrantyPeriodsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WarrantyPeriodsControllerBase {
  constructor(
    protected readonly service: WarrantyPeriodsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WarrantyPeriods })
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWarrantyPeriods(
    @common.Body() data: WarrantyPeriodsCreateInput
  ): Promise<WarrantyPeriods> {
    return await this.service.createWarrantyPeriods({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WarrantyPeriods] })
  @ApiNestedQuery(WarrantyPeriodsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async warrantyPeriodsItems(
    @common.Req() request: Request
  ): Promise<WarrantyPeriods[]> {
    const args = plainToClass(WarrantyPeriodsFindManyArgs, request.query);
    return this.service.warrantyPeriodsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WarrantyPeriods })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async warrantyPeriods(
    @common.Param() params: WarrantyPeriodsWhereUniqueInput
  ): Promise<WarrantyPeriods | null> {
    const result = await this.service.warrantyPeriods({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WarrantyPeriods })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWarrantyPeriods(
    @common.Param() params: WarrantyPeriodsWhereUniqueInput,
    @common.Body() data: WarrantyPeriodsUpdateInput
  ): Promise<WarrantyPeriods | null> {
    try {
      return await this.service.updateWarrantyPeriods({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WarrantyPeriods })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWarrantyPeriods(
    @common.Param() params: WarrantyPeriodsWhereUniqueInput
  ): Promise<WarrantyPeriods | null> {
    try {
      return await this.service.deleteWarrantyPeriods({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
