/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WarrantyPeriods } from "./WarrantyPeriods";
import { WarrantyPeriodsCountArgs } from "./WarrantyPeriodsCountArgs";
import { WarrantyPeriodsFindManyArgs } from "./WarrantyPeriodsFindManyArgs";
import { WarrantyPeriodsFindUniqueArgs } from "./WarrantyPeriodsFindUniqueArgs";
import { DeleteWarrantyPeriodsArgs } from "./DeleteWarrantyPeriodsArgs";
import { WarrantyPeriodsService } from "../warrantyPeriods.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => WarrantyPeriods)
export class WarrantyPeriodsResolverBase {
  constructor(
    protected readonly service: WarrantyPeriodsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "read",
    possession: "any",
  })
  async _warrantyPeriodsItemsMeta(
    @graphql.Args() args: WarrantyPeriodsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [WarrantyPeriods])
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "read",
    possession: "any",
  })
  async warrantyPeriodsItems(
    @graphql.Args() args: WarrantyPeriodsFindManyArgs
  ): Promise<WarrantyPeriods[]> {
    return this.service.warrantyPeriodsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => WarrantyPeriods, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "read",
    possession: "own",
  })
  async warrantyPeriods(
    @graphql.Args() args: WarrantyPeriodsFindUniqueArgs
  ): Promise<WarrantyPeriods | null> {
    const result = await this.service.warrantyPeriods(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => WarrantyPeriods)
  @nestAccessControl.UseRoles({
    resource: "WarrantyPeriods",
    action: "delete",
    possession: "any",
  })
  async deleteWarrantyPeriods(
    @graphql.Args() args: DeleteWarrantyPeriodsArgs
  ): Promise<WarrantyPeriods | null> {
    try {
      return await this.service.deleteWarrantyPeriods(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
