/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalLevelsAndRules } from "./ApprovalLevelsAndRules";
import { ApprovalLevelsAndRulesCountArgs } from "./ApprovalLevelsAndRulesCountArgs";
import { ApprovalLevelsAndRulesFindManyArgs } from "./ApprovalLevelsAndRulesFindManyArgs";
import { ApprovalLevelsAndRulesFindUniqueArgs } from "./ApprovalLevelsAndRulesFindUniqueArgs";
import { DeleteApprovalLevelsAndRulesArgs } from "./DeleteApprovalLevelsAndRulesArgs";
import { ApprovalLevelsAndRulesService } from "../approvalLevelsAndRules.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApprovalLevelsAndRules)
export class ApprovalLevelsAndRulesResolverBase {
  constructor(
    protected readonly service: ApprovalLevelsAndRulesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApprovalLevelsAndRules",
    action: "read",
    possession: "any",
  })
  async _approvalLevelsAndRulesItemsMeta(
    @graphql.Args() args: ApprovalLevelsAndRulesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApprovalLevelsAndRules])
  @nestAccessControl.UseRoles({
    resource: "ApprovalLevelsAndRules",
    action: "read",
    possession: "any",
  })
  async approvalLevelsAndRulesItems(
    @graphql.Args() args: ApprovalLevelsAndRulesFindManyArgs
  ): Promise<ApprovalLevelsAndRules[]> {
    return this.service.approvalLevelsAndRulesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApprovalLevelsAndRules, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApprovalLevelsAndRules",
    action: "read",
    possession: "own",
  })
  async approvalLevelsAndRules(
    @graphql.Args() args: ApprovalLevelsAndRulesFindUniqueArgs
  ): Promise<ApprovalLevelsAndRules | null> {
    const result = await this.service.approvalLevelsAndRules(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ApprovalLevelsAndRules)
  @nestAccessControl.UseRoles({
    resource: "ApprovalLevelsAndRules",
    action: "delete",
    possession: "any",
  })
  async deleteApprovalLevelsAndRules(
    @graphql.Args() args: DeleteApprovalLevelsAndRulesArgs
  ): Promise<ApprovalLevelsAndRules | null> {
    try {
      return await this.service.deleteApprovalLevelsAndRules(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
