/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PreventiveMaintenanceService } from "../preventiveMaintenance.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PreventiveMaintenanceCreateInput } from "./PreventiveMaintenanceCreateInput";
import { PreventiveMaintenance } from "./PreventiveMaintenance";
import { PreventiveMaintenanceFindManyArgs } from "./PreventiveMaintenanceFindManyArgs";
import { PreventiveMaintenanceWhereUniqueInput } from "./PreventiveMaintenanceWhereUniqueInput";
import { PreventiveMaintenanceUpdateInput } from "./PreventiveMaintenanceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PreventiveMaintenanceControllerBase {
  constructor(
    protected readonly service: PreventiveMaintenanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PreventiveMaintenance })
  @nestAccessControl.UseRoles({
    resource: "PreventiveMaintenance",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPreventiveMaintenance(
    @common.Body() data: PreventiveMaintenanceCreateInput
  ): Promise<PreventiveMaintenance> {
    return await this.service.createPreventiveMaintenance({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PreventiveMaintenance] })
  @ApiNestedQuery(PreventiveMaintenanceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PreventiveMaintenance",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async preventiveMaintenances(
    @common.Req() request: Request
  ): Promise<PreventiveMaintenance[]> {
    const args = plainToClass(PreventiveMaintenanceFindManyArgs, request.query);
    return this.service.preventiveMaintenances({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PreventiveMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PreventiveMaintenance",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async preventiveMaintenance(
    @common.Param() params: PreventiveMaintenanceWhereUniqueInput
  ): Promise<PreventiveMaintenance | null> {
    const result = await this.service.preventiveMaintenance({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PreventiveMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PreventiveMaintenance",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePreventiveMaintenance(
    @common.Param() params: PreventiveMaintenanceWhereUniqueInput,
    @common.Body() data: PreventiveMaintenanceUpdateInput
  ): Promise<PreventiveMaintenance | null> {
    try {
      return await this.service.updatePreventiveMaintenance({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PreventiveMaintenance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PreventiveMaintenance",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePreventiveMaintenance(
    @common.Param() params: PreventiveMaintenanceWhereUniqueInput
  ): Promise<PreventiveMaintenance | null> {
    try {
      return await this.service.deletePreventiveMaintenance({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
