/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ApprovalProcess } from "./ApprovalProcess";
import { ApprovalProcessCountArgs } from "./ApprovalProcessCountArgs";
import { ApprovalProcessFindManyArgs } from "./ApprovalProcessFindManyArgs";
import { ApprovalProcessFindUniqueArgs } from "./ApprovalProcessFindUniqueArgs";
import { DeleteApprovalProcessArgs } from "./DeleteApprovalProcessArgs";
import { ApprovalProcessService } from "../approvalProcess.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ApprovalProcess)
export class ApprovalProcessResolverBase {
  constructor(
    protected readonly service: ApprovalProcessService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ApprovalProcess",
    action: "read",
    possession: "any",
  })
  async _approvalProcessesMeta(
    @graphql.Args() args: ApprovalProcessCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ApprovalProcess])
  @nestAccessControl.UseRoles({
    resource: "ApprovalProcess",
    action: "read",
    possession: "any",
  })
  async approvalProcesses(
    @graphql.Args() args: ApprovalProcessFindManyArgs
  ): Promise<ApprovalProcess[]> {
    return this.service.approvalProcesses(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ApprovalProcess, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ApprovalProcess",
    action: "read",
    possession: "own",
  })
  async approvalProcess(
    @graphql.Args() args: ApprovalProcessFindUniqueArgs
  ): Promise<ApprovalProcess | null> {
    const result = await this.service.approvalProcess(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ApprovalProcess)
  @nestAccessControl.UseRoles({
    resource: "ApprovalProcess",
    action: "delete",
    possession: "any",
  })
  async deleteApprovalProcess(
    @graphql.Args() args: DeleteApprovalProcessArgs
  ): Promise<ApprovalProcess | null> {
    try {
      return await this.service.deleteApprovalProcess(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
