/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PayrollProcessing } from "./PayrollProcessing";
import { PayrollProcessingCountArgs } from "./PayrollProcessingCountArgs";
import { PayrollProcessingFindManyArgs } from "./PayrollProcessingFindManyArgs";
import { PayrollProcessingFindUniqueArgs } from "./PayrollProcessingFindUniqueArgs";
import { DeletePayrollProcessingArgs } from "./DeletePayrollProcessingArgs";
import { PayrollProcessingService } from "../payrollProcessing.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PayrollProcessing)
export class PayrollProcessingResolverBase {
  constructor(
    protected readonly service: PayrollProcessingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "read",
    possession: "any",
  })
  async _payrollProcessingsMeta(
    @graphql.Args() args: PayrollProcessingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PayrollProcessing])
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "read",
    possession: "any",
  })
  async payrollProcessings(
    @graphql.Args() args: PayrollProcessingFindManyArgs
  ): Promise<PayrollProcessing[]> {
    return this.service.payrollProcessings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PayrollProcessing, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "read",
    possession: "own",
  })
  async payrollProcessing(
    @graphql.Args() args: PayrollProcessingFindUniqueArgs
  ): Promise<PayrollProcessing | null> {
    const result = await this.service.payrollProcessing(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PayrollProcessing)
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "delete",
    possession: "any",
  })
  async deletePayrollProcessing(
    @graphql.Args() args: DeletePayrollProcessingArgs
  ): Promise<PayrollProcessing | null> {
    try {
      return await this.service.deletePayrollProcessing(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
