/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PayrollProcessingService } from "../payrollProcessing.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PayrollProcessingCreateInput } from "./PayrollProcessingCreateInput";
import { PayrollProcessing } from "./PayrollProcessing";
import { PayrollProcessingFindManyArgs } from "./PayrollProcessingFindManyArgs";
import { PayrollProcessingWhereUniqueInput } from "./PayrollProcessingWhereUniqueInput";
import { PayrollProcessingUpdateInput } from "./PayrollProcessingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PayrollProcessingControllerBase {
  constructor(
    protected readonly service: PayrollProcessingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PayrollProcessing })
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPayrollProcessing(
    @common.Body() data: PayrollProcessingCreateInput
  ): Promise<PayrollProcessing> {
    return await this.service.createPayrollProcessing({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PayrollProcessing] })
  @ApiNestedQuery(PayrollProcessingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payrollProcessings(
    @common.Req() request: Request
  ): Promise<PayrollProcessing[]> {
    const args = plainToClass(PayrollProcessingFindManyArgs, request.query);
    return this.service.payrollProcessings({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PayrollProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async payrollProcessing(
    @common.Param() params: PayrollProcessingWhereUniqueInput
  ): Promise<PayrollProcessing | null> {
    const result = await this.service.payrollProcessing({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PayrollProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePayrollProcessing(
    @common.Param() params: PayrollProcessingWhereUniqueInput,
    @common.Body() data: PayrollProcessingUpdateInput
  ): Promise<PayrollProcessing | null> {
    try {
      return await this.service.updatePayrollProcessing({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PayrollProcessing })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PayrollProcessing",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePayrollProcessing(
    @common.Param() params: PayrollProcessingWhereUniqueInput
  ): Promise<PayrollProcessing | null> {
    try {
      return await this.service.deletePayrollProcessing({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
