/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LeaveAndAttendanceManagement } from "./LeaveAndAttendanceManagement";
import { LeaveAndAttendanceManagementCountArgs } from "./LeaveAndAttendanceManagementCountArgs";
import { LeaveAndAttendanceManagementFindManyArgs } from "./LeaveAndAttendanceManagementFindManyArgs";
import { LeaveAndAttendanceManagementFindUniqueArgs } from "./LeaveAndAttendanceManagementFindUniqueArgs";
import { DeleteLeaveAndAttendanceManagementArgs } from "./DeleteLeaveAndAttendanceManagementArgs";
import { LeaveAndAttendanceManagementService } from "../leaveAndAttendanceManagement.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => LeaveAndAttendanceManagement)
export class LeaveAndAttendanceManagementResolverBase {
  constructor(
    protected readonly service: LeaveAndAttendanceManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "read",
    possession: "any",
  })
  async _leaveAndAttendanceManagementsMeta(
    @graphql.Args() args: LeaveAndAttendanceManagementCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [LeaveAndAttendanceManagement])
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "read",
    possession: "any",
  })
  async leaveAndAttendanceManagements(
    @graphql.Args() args: LeaveAndAttendanceManagementFindManyArgs
  ): Promise<LeaveAndAttendanceManagement[]> {
    return this.service.leaveAndAttendanceManagements(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => LeaveAndAttendanceManagement, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "read",
    possession: "own",
  })
  async leaveAndAttendanceManagement(
    @graphql.Args() args: LeaveAndAttendanceManagementFindUniqueArgs
  ): Promise<LeaveAndAttendanceManagement | null> {
    const result = await this.service.leaveAndAttendanceManagement(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LeaveAndAttendanceManagement)
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "delete",
    possession: "any",
  })
  async deleteLeaveAndAttendanceManagement(
    @graphql.Args() args: DeleteLeaveAndAttendanceManagementArgs
  ): Promise<LeaveAndAttendanceManagement | null> {
    try {
      return await this.service.deleteLeaveAndAttendanceManagement(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
