/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LeaveAndAttendanceManagementService } from "../leaveAndAttendanceManagement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LeaveAndAttendanceManagementCreateInput } from "./LeaveAndAttendanceManagementCreateInput";
import { LeaveAndAttendanceManagement } from "./LeaveAndAttendanceManagement";
import { LeaveAndAttendanceManagementFindManyArgs } from "./LeaveAndAttendanceManagementFindManyArgs";
import { LeaveAndAttendanceManagementWhereUniqueInput } from "./LeaveAndAttendanceManagementWhereUniqueInput";
import { LeaveAndAttendanceManagementUpdateInput } from "./LeaveAndAttendanceManagementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LeaveAndAttendanceManagementControllerBase {
  constructor(
    protected readonly service: LeaveAndAttendanceManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: LeaveAndAttendanceManagement })
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createLeaveAndAttendanceManagement(
    @common.Body() data: LeaveAndAttendanceManagementCreateInput
  ): Promise<LeaveAndAttendanceManagement> {
    return await this.service.createLeaveAndAttendanceManagement({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [LeaveAndAttendanceManagement] })
  @ApiNestedQuery(LeaveAndAttendanceManagementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async leaveAndAttendanceManagements(
    @common.Req() request: Request
  ): Promise<LeaveAndAttendanceManagement[]> {
    const args = plainToClass(
      LeaveAndAttendanceManagementFindManyArgs,
      request.query
    );
    return this.service.leaveAndAttendanceManagements({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: LeaveAndAttendanceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async leaveAndAttendanceManagement(
    @common.Param() params: LeaveAndAttendanceManagementWhereUniqueInput
  ): Promise<LeaveAndAttendanceManagement | null> {
    const result = await this.service.leaveAndAttendanceManagement({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: LeaveAndAttendanceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateLeaveAndAttendanceManagement(
    @common.Param() params: LeaveAndAttendanceManagementWhereUniqueInput,
    @common.Body() data: LeaveAndAttendanceManagementUpdateInput
  ): Promise<LeaveAndAttendanceManagement | null> {
    try {
      return await this.service.updateLeaveAndAttendanceManagement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: LeaveAndAttendanceManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "LeaveAndAttendanceManagement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteLeaveAndAttendanceManagement(
    @common.Param() params: LeaveAndAttendanceManagementWhereUniqueInput
  ): Promise<LeaveAndAttendanceManagement | null> {
    try {
      return await this.service.deleteLeaveAndAttendanceManagement({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
