/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EmployeeInformationManagementService } from "../employeeInformationManagement.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EmployeeInformationManagementCreateInput } from "./EmployeeInformationManagementCreateInput";
import { EmployeeInformationManagement } from "./EmployeeInformationManagement";
import { EmployeeInformationManagementFindManyArgs } from "./EmployeeInformationManagementFindManyArgs";
import { EmployeeInformationManagementWhereUniqueInput } from "./EmployeeInformationManagementWhereUniqueInput";
import { EmployeeInformationManagementUpdateInput } from "./EmployeeInformationManagementUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EmployeeInformationManagementControllerBase {
  constructor(
    protected readonly service: EmployeeInformationManagementService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EmployeeInformationManagement })
  @nestAccessControl.UseRoles({
    resource: "EmployeeInformationManagement",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEmployeeInformationManagement(
    @common.Body() data: EmployeeInformationManagementCreateInput
  ): Promise<EmployeeInformationManagement> {
    return await this.service.createEmployeeInformationManagement({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EmployeeInformationManagement] })
  @ApiNestedQuery(EmployeeInformationManagementFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EmployeeInformationManagement",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async employeeInformationManagements(
    @common.Req() request: Request
  ): Promise<EmployeeInformationManagement[]> {
    const args = plainToClass(
      EmployeeInformationManagementFindManyArgs,
      request.query
    );
    return this.service.employeeInformationManagements({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EmployeeInformationManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmployeeInformationManagement",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async employeeInformationManagement(
    @common.Param() params: EmployeeInformationManagementWhereUniqueInput
  ): Promise<EmployeeInformationManagement | null> {
    const result = await this.service.employeeInformationManagement({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EmployeeInformationManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmployeeInformationManagement",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEmployeeInformationManagement(
    @common.Param() params: EmployeeInformationManagementWhereUniqueInput,
    @common.Body() data: EmployeeInformationManagementUpdateInput
  ): Promise<EmployeeInformationManagement | null> {
    try {
      return await this.service.updateEmployeeInformationManagement({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EmployeeInformationManagement })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EmployeeInformationManagement",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEmployeeInformationManagement(
    @common.Param() params: EmployeeInformationManagementWhereUniqueInput
  ): Promise<EmployeeInformationManagement | null> {
    try {
      return await this.service.deleteEmployeeInformationManagement({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
