/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AdvanceTrackingService } from "../advanceTracking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdvanceTrackingCreateInput } from "./AdvanceTrackingCreateInput";
import { AdvanceTracking } from "./AdvanceTracking";
import { AdvanceTrackingFindManyArgs } from "./AdvanceTrackingFindManyArgs";
import { AdvanceTrackingWhereUniqueInput } from "./AdvanceTrackingWhereUniqueInput";
import { AdvanceTrackingUpdateInput } from "./AdvanceTrackingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AdvanceTrackingControllerBase {
  constructor(
    protected readonly service: AdvanceTrackingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AdvanceTracking })
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAdvanceTracking(
    @common.Body() data: AdvanceTrackingCreateInput
  ): Promise<AdvanceTracking> {
    return await this.service.createAdvanceTracking({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AdvanceTracking] })
  @ApiNestedQuery(AdvanceTrackingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async advanceTrackings(
    @common.Req() request: Request
  ): Promise<AdvanceTracking[]> {
    const args = plainToClass(AdvanceTrackingFindManyArgs, request.query);
    return this.service.advanceTrackings({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AdvanceTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async advanceTracking(
    @common.Param() params: AdvanceTrackingWhereUniqueInput
  ): Promise<AdvanceTracking | null> {
    const result = await this.service.advanceTracking({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AdvanceTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAdvanceTracking(
    @common.Param() params: AdvanceTrackingWhereUniqueInput,
    @common.Body() data: AdvanceTrackingUpdateInput
  ): Promise<AdvanceTracking | null> {
    try {
      return await this.service.updateAdvanceTracking({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AdvanceTracking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAdvanceTracking(
    @common.Param() params: AdvanceTrackingWhereUniqueInput
  ): Promise<AdvanceTracking | null> {
    try {
      return await this.service.deleteAdvanceTracking({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
