/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AdvanceTracking } from "./AdvanceTracking";
import { AdvanceTrackingCountArgs } from "./AdvanceTrackingCountArgs";
import { AdvanceTrackingFindManyArgs } from "./AdvanceTrackingFindManyArgs";
import { AdvanceTrackingFindUniqueArgs } from "./AdvanceTrackingFindUniqueArgs";
import { DeleteAdvanceTrackingArgs } from "./DeleteAdvanceTrackingArgs";
import { AdvanceTrackingService } from "../advanceTracking.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AdvanceTracking)
export class AdvanceTrackingResolverBase {
  constructor(
    protected readonly service: AdvanceTrackingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "read",
    possession: "any",
  })
  async _advanceTrackingsMeta(
    @graphql.Args() args: AdvanceTrackingCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AdvanceTracking])
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "read",
    possession: "any",
  })
  async advanceTrackings(
    @graphql.Args() args: AdvanceTrackingFindManyArgs
  ): Promise<AdvanceTracking[]> {
    return this.service.advanceTrackings(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AdvanceTracking, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "read",
    possession: "own",
  })
  async advanceTracking(
    @graphql.Args() args: AdvanceTrackingFindUniqueArgs
  ): Promise<AdvanceTracking | null> {
    const result = await this.service.advanceTracking(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AdvanceTracking)
  @nestAccessControl.UseRoles({
    resource: "AdvanceTracking",
    action: "delete",
    possession: "any",
  })
  async deleteAdvanceTracking(
    @graphql.Args() args: DeleteAdvanceTrackingArgs
  ): Promise<AdvanceTracking | null> {
    try {
      return await this.service.deleteAdvanceTracking(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
