/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssignedAssets } from "./AssignedAssets";
import { AssignedAssetsCountArgs } from "./AssignedAssetsCountArgs";
import { AssignedAssetsFindManyArgs } from "./AssignedAssetsFindManyArgs";
import { AssignedAssetsFindUniqueArgs } from "./AssignedAssetsFindUniqueArgs";
import { DeleteAssignedAssetsArgs } from "./DeleteAssignedAssetsArgs";
import { AssignedAssetsService } from "../assignedAssets.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AssignedAssets)
export class AssignedAssetsResolverBase {
  constructor(
    protected readonly service: AssignedAssetsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AssignedAssets",
    action: "read",
    possession: "any",
  })
  async _assignedAssetsItemsMeta(
    @graphql.Args() args: AssignedAssetsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AssignedAssets])
  @nestAccessControl.UseRoles({
    resource: "AssignedAssets",
    action: "read",
    possession: "any",
  })
  async assignedAssetsItems(
    @graphql.Args() args: AssignedAssetsFindManyArgs
  ): Promise<AssignedAssets[]> {
    return this.service.assignedAssetsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AssignedAssets, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AssignedAssets",
    action: "read",
    possession: "own",
  })
  async assignedAssets(
    @graphql.Args() args: AssignedAssetsFindUniqueArgs
  ): Promise<AssignedAssets | null> {
    const result = await this.service.assignedAssets(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AssignedAssets)
  @nestAccessControl.UseRoles({
    resource: "AssignedAssets",
    action: "delete",
    possession: "any",
  })
  async deleteAssignedAssets(
    @graphql.Args() args: DeleteAssignedAssetsArgs
  ): Promise<AssignedAssets | null> {
    try {
      return await this.service.deleteAssignedAssets(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
