/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { NotificationAndEscalation } from "./NotificationAndEscalation";
import { NotificationAndEscalationCountArgs } from "./NotificationAndEscalationCountArgs";
import { NotificationAndEscalationFindManyArgs } from "./NotificationAndEscalationFindManyArgs";
import { NotificationAndEscalationFindUniqueArgs } from "./NotificationAndEscalationFindUniqueArgs";
import { DeleteNotificationAndEscalationArgs } from "./DeleteNotificationAndEscalationArgs";
import { NotificationAndEscalationService } from "../notificationAndEscalation.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => NotificationAndEscalation)
export class NotificationAndEscalationResolverBase {
  constructor(
    protected readonly service: NotificationAndEscalationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "NotificationAndEscalation",
    action: "read",
    possession: "any",
  })
  async _notificationAndEscalationsMeta(
    @graphql.Args() args: NotificationAndEscalationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [NotificationAndEscalation])
  @nestAccessControl.UseRoles({
    resource: "NotificationAndEscalation",
    action: "read",
    possession: "any",
  })
  async notificationAndEscalations(
    @graphql.Args() args: NotificationAndEscalationFindManyArgs
  ): Promise<NotificationAndEscalation[]> {
    return this.service.notificationAndEscalations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => NotificationAndEscalation, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "NotificationAndEscalation",
    action: "read",
    possession: "own",
  })
  async notificationAndEscalation(
    @graphql.Args() args: NotificationAndEscalationFindUniqueArgs
  ): Promise<NotificationAndEscalation | null> {
    const result = await this.service.notificationAndEscalation(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => NotificationAndEscalation)
  @nestAccessControl.UseRoles({
    resource: "NotificationAndEscalation",
    action: "delete",
    possession: "any",
  })
  async deleteNotificationAndEscalation(
    @graphql.Args() args: DeleteNotificationAndEscalationArgs
  ): Promise<NotificationAndEscalation | null> {
    try {
      return await this.service.deleteNotificationAndEscalation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
